-- Auto-generated by scripts/gen_exercise_catalog.py
BEGIN;
INSERT INTO public.muscle_tags (code) VALUES
  ('chest'),
  ('front_delts'),
  ('side_delts'),
  ('rear_delts'),
  ('biceps'),
  ('triceps'),
  ('forearms'),
  ('traps'),
  ('lats'),
  ('upper_back'),
  ('lower_back'),
  ('abs'),
  ('obliques'),
  ('glutes'),
  ('quads'),
  ('hamstrings'),
  ('adductors'),
  ('calves'),
  ('hip_flexors'),
  ('tibialis_anterior')
ON CONFLICT (code) DO NOTHING;
COMMIT;
