#!/usr/bin/env python3
"""
Build production artifacts from scripts/exercise_catalog.tsv:
  - data/exercises.catalog.json
  - database/004_seed_muscle_tags.sql
  - database/005_seed_exercises_catalog.sql
  - shared/exerciseClassification.ts
"""
from __future__ import annotations

import csv
import json
import uuid
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TSV_PATH = ROOT / "scripts" / "exercise_catalog.tsv"
OUT_JSON = ROOT / "data" / "exercises.catalog.json"
OUT_MUSCLE_SQL = ROOT / "database" / "004_seed_muscle_tags.sql"
OUT_EX_SQL = ROOT / "database" / "005_seed_exercises_catalog.sql"
OUT_TS = ROOT / "shared" / "exerciseClassification.ts"

NS = uuid.UUID("6ba7b811-9dad-11d1-80b4-00c04fd430c8")  # URL namespace


MUSCLE_CODES = [
    "chest",
    "front_delts",
    "side_delts",
    "rear_delts",
    "biceps",
    "triceps",
    "forearms",
    "traps",
    "lats",
    "upper_back",
    "lower_back",
    "abs",
    "obliques",
    "glutes",
    "quads",
    "hamstrings",
    "adductors",
    "calves",
    "hip_flexors",
    "tibialis_anterior",
]


def exercise_uuid(slug: str) -> str:
    return str(uuid.uuid5(NS, f"schede.fitness/exercise/{slug}"))


def sql_escape(s: str) -> str:
    return s.replace("'", "''")


def load_rows():
    with TSV_PATH.open(encoding="utf-8") as f:
        return list(csv.DictReader(f, delimiter="\t"))


def row_to_exercise(row: dict) -> dict:
    slug = row["slug"]
    secondaries = [x.strip() for x in row["secondaries"].split(",") if x.strip()]
    tags = [x.strip() for x in row["tags"].split(",") if x.strip()]
    goals = [x.strip() for x in row["goals"].split(",") if x.strip()]
    is_uni = row["is_unilateral"].lower() == "true"
    return {
        "id": exercise_uuid(slug),
        "slug": slug,
        "name": row["name_it"],
        "primary_muscle": row["primary"],
        "secondary_muscles": secondaries,
        "movement_pattern": row["pattern"],
        "equipment": row["equipment"],
        "difficulty": row["difficulty"],
        "fatigue_score": int(row["fatigue"]),
        "stimulus_to_fatigue_ratio": float(row["sfr"]),
        "unilateral": is_uni,
        "bilateral": not is_uni,
        "stability_requirement": row["stability"],
        "skill_requirement": row["skill"],
        "force_curve": row["force_curve"],
        "exercise_type": row["ex_type"],
        "body_region": row["body_region"],
        "tags": tags,
        "compatible_goals": goals,
        "injury_risk": row["injury"],
        "estimated_setup_time_sec": int(row["setup_sec"]),
        "estimated_session_cost": row["session_cost"],
        "tempo_compatibility": row["tempo_comp"],
    }


def build_metadata(ex: dict) -> dict:
    return {
        "catalog_version": "1.0.0",
        "classification": "schede_biomech_v1",
        "primary_muscle_code": ex["primary_muscle"],
        "secondary_muscle_codes": ex["secondary_muscles"],
        "biomechanics": {
            "difficulty": ex["difficulty"],
            "fatigue_score": ex["fatigue_score"],
            "stimulus_to_fatigue_ratio": ex["stimulus_to_fatigue_ratio"],
            "stability_requirement": ex["stability_requirement"],
            "skill_requirement": ex["skill_requirement"],
            "force_curve": ex["force_curve"],
            "exercise_type": ex["exercise_type"],
            "injury_risk": ex["injury_risk"],
            "estimated_setup_time_sec": ex["estimated_setup_time_sec"],
            "estimated_session_cost": ex["estimated_session_cost"],
            "tempo_compatibility": ex["tempo_compatibility"],
        },
        "body_region": ex["body_region"],
        "tags": ex["tags"],
        "compatible_goals": ex["compatible_goals"],
    }


def validate_muscles(exercises: list[dict]):
    known = set(MUSCLE_CODES)
    for ex in exercises:
        if ex["primary_muscle"] not in known:
            raise ValueError(f"Unknown primary muscle {ex['primary_muscle']} in {ex['slug']}")
        for m in ex["secondary_muscles"]:
            if m not in known:
                raise ValueError(f"Unknown secondary muscle {m} in {ex['slug']}")


def write_muscle_sql():
    lines = [
        "-- Auto-generated by scripts/gen_exercise_catalog.py",
        "BEGIN;",
        "INSERT INTO public.muscle_tags (code) VALUES",
    ]
    vals = ",\n".join(f"  ('{sql_escape(c)}')" for c in MUSCLE_CODES)
    lines.append(vals + "\nON CONFLICT (code) DO NOTHING;")
    lines.append("COMMIT;")
    OUT_MUSCLE_SQL.parent.mkdir(parents=True, exist_ok=True)
    OUT_MUSCLE_SQL.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_exercise_sql(exercises: list[dict]):
    lines = [
        "-- Auto-generated by scripts/gen_exercise_catalog.py",
        "-- Requires: 001_initial_schema.sql applied; run after 004_seed_muscle_tags.sql",
        "BEGIN;",
    ]
    for ex in exercises:
        meta = build_metadata(ex)
        meta_json = json.dumps(meta, ensure_ascii=False)
        eid = ex["id"]
        pat = ex["movement_pattern"]
        eq = ex["equipment"]
        uni = "true" if ex["unilateral"] else "false"
        lines.append(
            f"INSERT INTO public.exercises (id, slug, is_custom, equipment, pattern, is_unilateral, metadata)\n"
            f"VALUES ('{eid}'::uuid, '{sql_escape(ex['slug'])}', false, '{eq}'::public.equipment_type, "
            f"'{pat}'::public.movement_pattern, {uni}, '{sql_escape(meta_json)}'::jsonb)\n"
            f"ON CONFLICT (slug) DO UPDATE SET\n"
            f"  equipment = EXCLUDED.equipment,\n"
            f"  pattern = EXCLUDED.pattern,\n"
            f"  is_unilateral = EXCLUDED.is_unilateral,\n"
            f"  metadata = EXCLUDED.metadata,\n"
            f"  updated_at = timezone('utc', now());"
        )
        name = sql_escape(ex["name"])
        lines.append(
            f"INSERT INTO public.exercise_translations (exercise_id, locale, name, description, coaching_cues)\n"
            f"VALUES ('{eid}'::uuid, 'it-IT', '{name}', NULL, NULL)\n"
            f"ON CONFLICT (exercise_id, locale) DO UPDATE SET name = EXCLUDED.name;"
        )
        lines.append(
            f"DELETE FROM public.exercise_muscles WHERE exercise_id = '{eid}'::uuid;"
        )
        lines.append(
            "INSERT INTO public.exercise_muscles (exercise_id, muscle_id, is_primary)\n"
            f"SELECT '{eid}'::uuid, mt.id, true\nFROM public.muscle_tags mt WHERE mt.code = '{sql_escape(ex['primary_muscle'])}';"
        )
        for m in ex["secondary_muscles"]:
            lines.append(
                "INSERT INTO public.exercise_muscles (exercise_id, muscle_id, is_primary)\n"
                f"SELECT '{eid}'::uuid, mt.id, false\nFROM public.muscle_tags mt WHERE mt.code = '{sql_escape(m)}';"
            )
    lines.append("COMMIT;")
    OUT_EX_SQL.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_ts():
    ts = r'''/**
 * Exercise classification + catalog types (schede_biomech_v1)
 * Auto-generated enums mirror scripts/gen_exercise_catalog.py — edit script + re-run to extend.
 */

export const EXERCISE_CLASSIFICATION_VERSION = 'schede_biomech_v1' as const;

export type MovementPattern =
  | 'squat'
  | 'hinge'
  | 'horizontal_push'
  | 'vertical_push'
  | 'horizontal_pull'
  | 'vertical_pull'
  | 'carry'
  | 'core_anti_extension'
  | 'core_anti_rotation'
  | 'other';

export type EquipmentType =
  | 'barbell'
  | 'dumbbell'
  | 'kettlebell'
  | 'machine'
  | 'cable'
  | 'band'
  | 'bodyweight'
  | 'smith_machine'
  | 'other';

/** 1–10: global fatigue / systemic cost proxy (CNS + local + cardio stress) */
export type FatigueScore = number;

/**
 * Higher = more hypertrophy/strength stimulus per unit fatigue.
 * Heuristic scale ~0.5–1.5; tune in analytics, not enforced in DB.
 */
export type StimulusToFatigueRatio = number;

export type DifficultyLevel = 'beginner' | 'intermediate' | 'advanced' | 'elite';

export type StabilityRequirement = 'low' | 'moderate' | 'high' | 'very_high';

export type SkillRequirement = 'low' | 'moderate' | 'high' | 'very_high';

/** Length–tension & external loading shape */
export type ForceCurve = 'descending' | 'flat' | 'ascending' | 'bell_shaped';

export type ExerciseType =
  | 'compound'
  | 'isolation'
  | 'isometric'
  | 'plyometric'
  | 'carry'
  | 'conditioning';

export type BodyRegion = 'upper' | 'lower' | 'core' | 'full';

export type InjuryRiskLevel = 'low' | 'moderate' | 'high';

/** Time to set up equipment / station (seconds) */
export type EstimatedSetupTimeSec = number;

/** Session cost: metabolic + systemic fatigue density */
export type SessionCostLevel = 'low' | 'medium' | 'high' | 'very_high';

/** How well tempo prescriptions (e.g. 3-0-1-0) apply without ruining technique */
export type TempoCompatibility = 'low' | 'medium' | 'high';

export type FitnessGoalCode =
  | 'strength'
  | 'muscle_gain'
  | 'fat_loss'
  | 'endurance'
  | 'general_fitness'
  | 'sport_specific'
  | 'rehab';

/** Normalized muscle codes (matches muscle_tags.code) */
export type MuscleCode =
'''
    for i, c in enumerate(MUSCLE_CODES):
        line = f"  | '{c}'"
        if i < len(MUSCLE_CODES) - 1:
            line += "\n"
        else:
            line += ";\n"
        ts += line

    ts += r'''
export interface ExerciseBiomechanics {
  difficulty: DifficultyLevel;
  fatigue_score: FatigueScore;
  stimulus_to_fatigue_ratio: StimulusToFatigueRatio;
  stability_requirement: StabilityRequirement;
  skill_requirement: SkillRequirement;
  force_curve: ForceCurve;
  exercise_type: ExerciseType;
  injury_risk: InjuryRiskLevel;
  estimated_setup_time_sec: EstimatedSetupTimeSec;
  estimated_session_cost: SessionCostLevel;
  tempo_compatibility: TempoCompatibility;
}

/** Stored in public.exercises.metadata + flat row in JSON catalog */
export interface ExerciseCatalogMetadata {
  catalog_version: string;
  classification: typeof EXERCISE_CLASSIFICATION_VERSION;
  primary_muscle_code: MuscleCode;
  secondary_muscle_codes: MuscleCode[];
  biomechanics: ExerciseBiomechanics;
  body_region: BodyRegion;
  tags: string[];
  compatible_goals: FitnessGoalCode[];
}

export interface ExerciseCatalogEntry {
  id: string;
  slug: string;
  name: string;
  primary_muscle: MuscleCode;
  secondary_muscles: MuscleCode[];
  movement_pattern: MovementPattern;
  equipment: EquipmentType;
  difficulty: DifficultyLevel;
  fatigue_score: FatigueScore;
  stimulus_to_fatigue_ratio: StimulusToFatigueRatio;
  unilateral: boolean;
  bilateral: boolean;
  stability_requirement: StabilityRequirement;
  skill_requirement: SkillRequirement;
  force_curve: ForceCurve;
  exercise_type: ExerciseType;
  body_region: BodyRegion;
  tags: string[];
  compatible_goals: FitnessGoalCode[];
  injury_risk: InjuryRiskLevel;
  estimated_setup_time_sec: EstimatedSetupTimeSec;
  estimated_session_cost: SessionCostLevel;
  tempo_compatibility: TempoCompatibility;
}

/**
 * Tag vocabulary (open set). Grouped for UX filters / AI program generation.
 * New exercises may introduce new strings; validate in app layer if you need a closed set.
 */
export const BIOMECHANICAL_TAG_CATEGORIES = {
  kinematics: [
    'knee_dominant',
    'hip_dominant',
    'vertical_pulling',
    'horizontal_pull',
    'pressing',
    'unilateral',
    'axial_load',
    'overhead_stability',
  ],
  context: ['home_gym', 'calisthenics', 'machine_based', 'competition_lift', 'conditioning_metcon'],
  loading_physiology: ['time_under_tension', 'constant_tension', 'accommodating_resistance', 'isometric_endurance'],
  coaching: ['warmup_activation', 'shoulder_health', 'spinal_unload', 'weak_point', 'skill_progression'],
} as const;

/** Any snake_case tag from catalog JSON */
export type ExerciseTag = string;

export function isCatalogTag(x: string): x is ExerciseTag {
  return typeof x === 'string' && x.length > 0 && /^[a-z0-9_]+$/.test(x);
}
'''
    OUT_TS.parent.mkdir(parents=True, exist_ok=True)
    OUT_TS.write_text(ts, encoding="utf-8")


def main():
    rows = load_rows()
    exercises = [row_to_exercise(r) for r in rows]
    validate_muscles(exercises)
    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    OUT_JSON.write_text(json.dumps(exercises, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    write_muscle_sql()
    write_exercise_sql(exercises)
    write_ts()
    print(f"Wrote {len(exercises)} exercises -> {OUT_JSON.relative_to(ROOT)}")
    print(f"SQL -> {OUT_MUSCLE_SQL.relative_to(ROOT)}, {OUT_EX_SQL.relative_to(ROOT)}")
    print(f"Types -> {OUT_TS.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
